src/Entity/Tournament.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TournamentRepository")
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Ce titre n'est pas disponible."
 * )
 */
class Tournament
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=50)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $team;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=2, max=100)
     */
    private $size;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min=1, max=10)
     */
    private $teamMinSize;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(max=10)
     */
    private $teamMaxSize;

    /**
     * @ORM\Column(type="boolean")
     */
    private $public;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="Tournaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tournaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state;

    /**
     * @Assert\Callback
     * @param ExecutionContextInterface $context
     * @param $payload
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if($this->getTeamMaxSize()<$this->getTeamMinSize()){
            $context->buildViolation("La valeur de ce champ doit être supérieur à la taille de l'équipe")
            ->atPath('teamMaxSize')
            ->addViolation();
        }

        if($this->getTeam() == 0 && $this->getTeamMinSize() !== 1){
            $context->buildViolation("La taille de l'équipe doit être de 1 pour un tournoi en Solo")
                ->atPath('teamMinSize')
                ->addViolation();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTeam(): ?bool
    {
        return $this->team;
    }

    public function setTeam(bool $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getTeamMinSize(): ?int
    {
        return $this->teamMinSize;
    }

    public function setTeamMinSize(int $teamMinSize): self
    {
        $this->teamMinSize = $teamMinSize;

        return $this;
    }

    public function getTeamMaxSize(): ?int
    {
        return $this->teamMaxSize;
    }

    public function setTeamMaxSize(int $teamMaxSize): self
    {
        $this->teamMaxSize = $teamMaxSize;

        return $this;
    }

    public function getPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }
}

src/Form/TournamentType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\SuperCategory;
use App\Entity\Tournament;
use App\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\Query\Expr\Join;

class TournamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        switch($options['flow_step'])
        {
            case 1:

                $builder->add('Category', EntityType::class, [
                    'class' => Category::class,
                    'query_builder' => function(CategoryRepository $categoryRepository) use ($options) {
                      return $categoryRepository->findAllBySuperCategoryCode($options['code']);
                    },
                    'choice_label' => 'Title'
                ]);
                break;
            case 2:
                $builder->add('title')
                    ->add('description', TextareaType::class, [
                        'attr' => array('rows' => 5)
                    ]);
                break;


        }

//        $builder
//            ->add('title')
//            ->add('description', TextareaType::class, [
//                'attr' => array('rows' => 5)
//            ])
//            ->add('category', EntityType::class, [
//                'class' => Category::class,
//                'choice_label' => 'Title'
//            ])
//            ->add('team', ChoiceType::class, [
//                'choices' => $this->getTeamChoices()
//            ])
//            ->add('public', ChoiceType::class, [
//                'choices' => $this->getPublicChoices()
//            ])
//            ->add('size')
//            ->add('teamMinSize', NumberType::class, array(
//                'required' => false,
//                'empty_data' => 1
//            ))
//            ->add('teamMaxSize', NumberType::class, array(
//                'required' => false,
//                'empty_data' => 1
//            ))
//        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tournament::class,
            'translation_domain' => 'forms',
            'code' => null,
        ]);
    }

    private function getTeamChoices()
    {
        $output = [];
        $output['Solo'] = 0;
        $output['Équipe'] = 1;
        return $output;
    }

    private function getPublicChoices()
    {
        $output = [];
        $output['Tournoi Public'] = 1;
        $output['Tournoi Privé'] = 0;
        return $output;
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Tournament;
use App\Form\TournamentFlow;
use App\Form\TournamentType;
use App\Repository\CategoryRepository;
use App\Repository\SuperCategoryRepository;
use App\Repository\TournamentRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TournamentController extends AbstractController
{

    /**
     * @var ObjectManager
     */
    private $em;
    /**
     * @var TournamentFlow
     */
    private $tournamentFlow;

    public function __construct(ObjectManager $em, TournamentFlow $tournamentFlow)
    {
        $this->em = $em;
        $this->tournamentFlow = $tournamentFlow;
    }

    /**
     * @Route("/", name="home")
    */
    public function index(){
        return $this->redirectToRoute('tournaments');
    }

    /**
     * @Route("/tournaments", name="tournaments")
     * @param TournamentRepository $repo
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function tournaments(TournamentRepository $repo)
    {
        $tournaments = $repo->findAll();
        return $this->render('tournament/tournaments.html.twig', [
            'tournaments' => $tournaments
        ]);
    }

    /**
     * @Route("/tournament/create", name="tournament_create")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function createTournament(SuperCategoryRepository $repo){
        $this->denyAccessUnlessGranted('ROLE_USER');


    }

    /**
     * @Route("/tournament/create", name="tournament_create")
     * @Route("/tournament/create/{code}", name="tournament_create_code")
     * @Method("GET")
     * @param Request $request
     * @param null $code
     * @param SuperCategoryRepository $repo
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function createTournamentCode(Request $request, $code = null, SuperCategoryRepository $repo){
        $this->denyAccessUnlessGranted('ROLE_USER');
        if($code === null){
            $superCategories = $repo->findAll();
            return $this->render('tournament/choose_super_category.html.twig', [
                'superCategories' => $superCategories
            ]);
        }else{
            $tournament = new Tournament();

            $flow = $this->tournamentFlow;
            $flow->setGenericFormOptions(['code' => $code]);
            $flow->bind($tournament);

            // form of the current step
            $form = $flow->createForm();
            if ($flow->isValid($form)) {
                $flow->saveCurrentStepData($form);

                if ($flow->nextStep()) {
                    // form for the next step
                    $form = $flow->createForm();
                } else {
                    // flow finished
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($tournament);
                    $em->flush();

                    $flow->reset(); // remove step data from the session

                    return $this->redirect($this->generateUrl('home')); // redirect when done
                }
            }

            return $this->render('tournament/create.html.twig', [
                'form' => $form->createView(),
                'flow' => $flow,
            ]);
        }
    }

    /**
     * @Route("tournament/{id}/edit", name="tournament_edit")
     * @param Tournament $tournament
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editTournament(Tournament $tournament, Request $request){
        if($this->getUser() === $tournament->getUser()){
            $form = $this->createForm(TournamentType::class, $tournament);
            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()){
                $this->em->flush();
                $this->addFlash('success', 'Tournoi modifié avec succès');
                return $this->redirectToRoute('tournament', array("id" => $tournament->getId()));
            }
            return $this->render('tournament/edit.html.twig', [
                'tournament' => $tournament,
                'form' => $form->createView()
            ]);
        }else{
            $this->addFlash('error', 'Vous n\'êtes pas le créateur de ce tournoi');
            return $this->redirectToRoute('tournaments');
        }

    }

    /**
     * @Route("tournament/{id}/delete", name="tournament_delete", methods="DELETE")
     * @param Tournament $tournament
     * @param Request $request
     */
    public function deleteTournament(Tournament $tournament, Request $request){
        if($this->getUser() === $tournament->getUser()) {
            if ($this->isCsrfTokenValid('delete' . $tournament->getId(), $request->get('_token'))) {
                $this->em->remove($tournament);
                $this->em->flush();
                $this->addFlash('success', 'Tournoi supprimé avec succès');
            }
            return $this->redirectToRoute('tournaments');
        }else{
            $this->addFlash('error', 'Vous n\'êtes pas le créateur de ce tournoi');
            return $this->redirectToRoute('tournaments');
        }
    }

    /**
     * @Route("/tournament/{id}", name="tournament")
     * @param Tournament $tournament
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function tournament(Tournament $tournament)
    {
        return $this->render('tournament/tournament.html.twig', [
            'tournament' => $tournament
        ]);
    }



}

templates/tournament/_tournamentForm.html.twig
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3 text-right">
                Étapes
            </div>
            <div class="col-md-9">
                {% include '@CraueFormFlow/FormFlow/stepList.html.twig' %}
            </div>
        </div>
        {{ form_start(form) }}
        {{ form_errors(form) }}

        {{ form_rest(form) }}

        {% include '@CraueFormFlow/FormFlow/buttons.html.twig'  with {
            craue_formflow_button_class_last: 'btn btn-success',
            craue_formflow_button_class_back: 'btn btn-secondary',
            craue_formflow_button_render_reset: false
        } %}
        {{ form_end(form) }}
    </div>
</div>

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="{{ asset('js/tournament/tournamentForm.js') }}" type="text/javascript"></script>
{% endblock %}

templates/tournament/choose_super_category.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Création d'un tournoi</h2>
    <hr>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h4>Type de tournoi</h4>
                    <hr>
                </div>
            </div>
            <div class="row">
                {% for superCategory in superCategories %}
                    <div class="col-md-4 center-block text-center">
                        <b>{{ superCategory.title }}</b>
                        <div class="card">
                            <a class="btn btn-primary btn-lg btn-super-category text-right" style="background-image: url('{{ superCategory.Image }}');" href="{{ path('tournament_create_code', {'code' : superCategory.Code}) }}">
                                <br>
                                <i class="fa fa-hand-point-up"></i><br>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tournament/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Création d'un tournoi</h2>
    <hr>
    {{ include('tournament/_tournamentForm.html.twig', {form: form, button: 'Créer le tournoi'}) }}
{% endblock %}

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Édition d'un tournoi</h2>
    <hr>
    {{ include('tournament/_tournamentForm.html.twig', {form: form, button: 'Éditer le tournoi'}) }}
{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Bienvenue dans Tournament</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid atque, eum molestiae numquam quibusdam quis rerum unde voluptas voluptatem. Accusamus aliquam at aut cupiditate dignissimos dolores, eos fuga fugiat inventore ipsa iste iure maiores molestiae molestias nihil nulla provident.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus adipisci aspernatur autem consectetur distinctio dolore dolorem ea expedita explicabo facilis fuga impedit iste magnam maiores minima molestiae mollitia nesciunt, optio, quo ratione repellendus rerum sapiente similique sint unde, veniam vero!</p>
{% endblock %}

templates/tournament/tournament.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <h2>{{ tournament.title }}</h2>
        </div>
        <div class="card-body">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {%  endfor %}
            <div class="row">
                <div class="col-6 border-right-default">
                    <div class="alert alert-info">
                        Par <b>{{ tournament.user.username }}</b> le {{ tournament.createdAt | date('d/m/Y')}}
                    </div>
                    <div class="text-center">
                        <h5>{{ tournament.category.title }}</h5>
                        <div class="container">
                            <img src="{{ tournament.category.image }}" class="categoryImg" alt="categorie">
                        </div>
                    </div>
                    <p>
                        <b>Etat:</b>
                        {% if tournament.state == 1 %}
                            Ouvert
                        {% else %}
                            Fermé
                        {% endif %}
                    </p>
                    <p>
                        <b>Informations</b>
                    <ul>
                        {% if tournament.public == true %}
                            <li>Public</li>
                        {% else %}
                            <li>Privé</li>
                        {% endif %}
                        {% if tournament.team == true %}
                            <li>Tournoi en équipes de {{ tournament.teamMinSize }}</li>
                        {% else %}
                            <li>Tournoi en solo</li>
                        {% endif %}
                        <li>{{ tournament.size }} participants</li>
                        <li>Débute le dd/mm/YY</li>
                    </ul>
                    </p>
                </div>
                <div class="col-6">
                    <p>
                        <b>Description :</b>
                        <p>
                            {{ tournament.description }}
                        </p>
                    </p>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <a class="btn btn-primary" href="">S'inscrire</a>
            {% if app.user == tournament.user %}
                <a class="btn btn-primary" href="{{ path('tournament_edit', {'id' : tournament.id}) }}">Editer</a>
                <form method="post" action="{{ path('tournament_delete', {id: tournament.id}) }}" style="display:inline-block" onsubmit="return confirm('Voulez-vous vraiment supprimer ce tournoi?');">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
                    <button class="btn btn-danger">Supprimer</button>
                </form>
            {% endif %}
            </section>
        </div>
    </div>
{% endblock %}

templates/tournament/tournaments.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Liste des Tournois publics</h2>
    <hr>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {%  endfor %}
    {% for message in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
    {%  endfor %}
    <div class="row">
        {%  for tournament in tournaments %}
            <div class="tournament col-md-3">
                <div class="card">
                    <img class="card-img-top" src="{{ tournament.category.image }}" alt="categorie">
                    <div class="card-body">
                        <div class="card-title text-center"><h5><a href="{{ path('tournament', {'id' : tournament.id}) }}">{{ tournament.title }}</a></h5></div>
                        <b>{{ tournament.category.title }}</b>
                        <p>Créé le {{ tournament.createdAt | date('d/m/Y')}} à {{ tournament.createdAt | date('H:i')}} par {{ tournament.user.username }}</p>
                        <p>
                            <b>Etat:</b>
                            {% if tournament.state == 1 %}
                                Ouvert
                            {% else %}
                                Fermé
                            {% endif %}
                        </p>
                        <p>
                            <b>Informations</b>
                        <ul>
                            <li>Équipes de {{ tournament.teamMinSize }} personnes</li>
                            <li>{{ tournament.size }} équipes</li>
                            <li>Débute le dd/mm/YY</li>
                        </ul>
                        </p>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{{ path('tournament', {'id' : tournament.id}) }}" class="btn btn-primary">Consulter</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}